// <auto-generated />
namespace edX.DataApp.Console.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddInternalId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInternalId));
        
        string IMigrationMetadata.Id
        {
            get { return "201707012132494_AddInternalId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
