//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edX.DataApp.Console.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int PartnerId { get; set; }
        public bool IsOpen { get; set; }
        public decimal AnnualRevenue { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int Priority { get; set; }
        public Nullable<System.Guid> InternalId { get; set; }
    }
}
