//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edX.DataApp.Console.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsDetailedView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ModelNumber { get; set; }
        public string Color { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string Category { get; set; }
    }
}
